<?
$PERM["desktop_app"]["*"]="D";
$PERM["online"]["*"]="R";
$PERM["upload"]["10"]="T_8";
$PERM["project"]["5"]="W";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>